// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Gauge = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Gauge, &ui_img_gauge_png);
    lv_obj_set_width(ui_Gauge, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Gauge, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_align(ui_Gauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Pointer = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Pointer, &ui_img_pointer_png);
    lv_obj_set_width(ui_Pointer, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Pointer, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Pointer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pointer, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Pointer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
